### ISSUE TITLE
OfficeViewer does not show ppt or xls

### ISSUE THREAD

**Issue by FrankITG** [iceteagroup/Wisej-DemoBrowser#45]
The buttons don´t seem to have any effect.

**Comment by AlaaTrAce** [comment]
It looks like something is blocking the widget from updating the file source or stream, tried various things and even recreating the widget failed.
I guess I need some help with this one

**Comment by LRufenacht** [comment]
Fixed and checked in.

The issue was that when setting a new FileStream to the Viewer it would use the same URL as before, preventing the IFramePanel from recognizing the difference and updating the client. The solution is to add a version argument (it was there in 2.2 but looks like it was removed in 2.5 / 3.0).
